name: nono rush

on:
  schedule:
    - cron: '11 6 * * *'

env:
  E_AMUSEMENT_ID: ${{ secrets.E_AMUSEMENT_ID }}
  E_AMUSEMENT_PW: ${{ secrets.E_AMUSEMENT_PW }}

jobs:
  nono-rush:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '14'
    - run: yarn
    - run: yarn start:nono-rush
